# Generated by Django 5.1 on 2025-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_studentprofile_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cerifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
