# Generated by Django 5.1 on 2025-03-18 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_competitiontype_sdg_skill_mentorprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
