# Generated by Django 5.1 on 2025-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentprofile_cerifications_studentprofile_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='cerifications',
            new_name='certifications',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='internships',
            field=models.TextField(blank=True, null=True),
        ),
    ]
