# Generated by Django 5.1 on 2025-03-19 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_mentorprofile_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('limited', 'Limited Availability'), ('unavailable', 'Unavailable')], default='available', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='available_days',
            field=models.CharField(blank=True, help_text='E.g., Monday, Wednesday', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='available_times',
            field=models.CharField(blank=True, help_text='E.g., 10am - 2pm', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='List of certifications', null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='competition_types',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='home.competitiontype'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='current_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='current_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='current_teams_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expertise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], default='prefer_not_to_say', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Comma separated languages', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='Maximum number of teams to mentor simultaneously', null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='mentor_type',
            field=models.CharField(blank=True, choices=[('faculty', 'Faculty'), ('industry', 'Industry Expert'), ('alumni', 'Alumni'), ('other', 'Other')], default='faculty', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='past_mentorship_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in format: '+999999999'")]),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='home.skill'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
