# Generated by Django 5.1 on 2025-03-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_cerifications_studentprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
