# Generated by Django 5.1 on 2025-03-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_studentprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
    ]
