# Generated by Django 5.1 on 2025-03-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Host',
        ),
    ]
