# Generated by Django 5.1 on 2025-03-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_admin_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_picture',
            field=models.ImageField(blank=True, null=True, upload_to='competition_picture/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('HOST', 'Host'), ('MENTOR', 'Mentor'), ('MANAGEMENT', 'Management')], default='STUDENT', max_length=20),
        ),
    ]
