# Generated by Django 5.1 on 2025-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_competition_competition_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_team_size',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
