# Generated by Django 5.1 on 2025-03-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_team_max_team_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project_title',
        ),
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
