# Generated by Django 5.1 on 2025-03-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_team_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
