# Generated by Django 5.1 on 2025-04-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
