# Generated by Django 5.1 on 2025-04-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_collaborationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='home.studentprofile')),
                ('to_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_consultations', to='home.mentorprofile')),
            ],
        ),
    ]
